name: itp4523m

services:
  php:
    container_name: itp4523m
    build:
      context: .
      dockerfile: php.Dockerfile
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    environment:
      HOST_HOSTNAME: host.docker.internal
      DB_HOSTNAME: database
    volumes:
      - ./htdocs:/var/www/html
  database:
    container_name: itp4523m-database
    image: mariadb:11
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: ProjectDB
      MARIADB_USER: itp4523m
      MARIADB_PASSWORD: itp4523m
      # MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_ROOT_PASSWORD: ""
    volumes:
      - ./CreateProjectDB.sql:/docker-entrypoint-initdb.d/CreateProjectDB.sql:ro
    tmpfs:
      - /var/lib/mysql

networks:
  backend:
