name: itp4523m

services:
  php:
    container_name: itp4523m
    image: php:8-apached
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - ./htdocs:/var/www/html
  database:
    container_name: itp4523m-database
    image: mariadb:11d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend
    environment:
      MARIADB_DATABASE: itp4523m
      MARIADB_USER: itp4523m
      MARIADB_PASSWORD: itp4523m
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./CreateProjectDB.sql:/docker-entrypoint-initdb.d/CreateProjectDB.sql:ro

networks:
  backend:
