<?php

$DB_HOSTNAME = $_ENV["DB_HOSTNAME"] ?? "127.0.0.1";
$DB_USERNAME = "root";
$DB_PASSWORD = "";
$DB_DATABASE = "ProjectDB";

$database = new mysqli($DB_HOSTNAME, $DB_USERNAME, $DB_PASSWORD, $DB_DATABASE);

unset($DB_HOSTNAME, $DB_USERNAME, $DB_PASSWORD, $DB_DATABASE);
